FROM apache/airflow:2.8.1-python3.11

# Install additional python packages needed by the DAGs
# Airflow base image already contains Airflow. Install only project-specific libs needed by DAGs.
COPY requirements-airflow.txt /tmp/requirements-airflow.txt
RUN pip install --no-cache-dir -r /tmp/requirements-airflow.txt

# Create DAGs directory
RUN mkdir -p /opt/airflow/dags

# Set working directory
WORKDIR /opt/airflow 