FROM apache/airflow:2.8.1-python3.11

# Installieren Sie Airflow-Abhängigkeiten und Ihre spezifischen Pakete
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir "apache-airflow[postgres,celery]==2.8.1" -r /tmp/requirements.txt

# Erstellen Sie den dags Ordner
RUN mkdir -p /opt/airflow/dags

# Setzen Sie das Arbeitsverzeichnis
WORKDIR /opt/airflow 